import gc
import os
import datetime
import tqdm
import torch
import contextlib
import wandb
import torchvision

from collections import defaultdict
from functools import partial

from ml_collections import config_flags
from flask import config
from absl import app, flags

from accelerate import Accelerator
from accelerate.utils import set_seed, ProjectConfiguration
from accelerate.logging import get_logger

from data import get_data_loader, get_synth_train_data_loader

from diffusers import StableDiffusionPipeline, DDIMScheduler
from models import TinyDecoder, CLIP
from cluster import get_centroids_from_loader_v2
from data import get_transforms

import torch.nn.functional as F

from iqsi import train_step, train_step_with_hard_samples, evaluate
tqdm = partial(tqdm.tqdm, dynamic_ncols=True)

FLAGS = flags.FLAGS
config_flags.DEFINE_config_file("config", "config/config.py", "Training configuration.")

logger = get_logger(__name__)

def flatten_config(config_dict, prefix=''):
    items = []
    for k, v in config_dict.items():
        new_key = f"{prefix}/{k}" if prefix else k
        if isinstance(v, dict):
            items.extend(flatten_config(v, new_key).items())
        else:
            if v is None:
                v = "None"
            elif not isinstance(v, (int, float, str, bool, torch.Tensor)):
                v = str(v)
            items.append((new_key, v))
    return dict(items)

def main(argv):
    del argv
    config = FLAGS.config
    
    unique_id = datetime.datetime.now().strftime("%Y.%m.%d_%H.%M.%S")
    if not config.run_name:
        config.run_name = unique_id
    else:
        config.run_name += "_" + unique_id

    if config.resume_from:
        config.resume_from = os.path.normpath(os.path.expanduser(config.resume_from))
        if "checkpoint_" not in os.path.basename(config.resume_from):
            # get the most recent checkpoint in this directory
            checkpoints = list(
                filter(lambda x: "checkpoint_" in x, os.listdir(config.resume_from))
            )
            if len(checkpoints) == 0:
                raise ValueError(f"No checkpoints found in {config.resume_from}")
            config.resume_from = os.path.join(
                config.resume_from,
                sorted(checkpoints, key=lambda x: int(x.split("_")[-1]))[-1],
            )

    accelerator_config = ProjectConfiguration(
        project_dir=os.path.join(config.logdir, config.run_name),
        automatic_checkpoint_naming=True,
        total_limit=config.num_checkpoint_limit,
    )

    accelerator = Accelerator(
        log_with=config.log_with,
        mixed_precision=config.mixed_precision,
        project_config=accelerator_config
    )

    set_seed(config.seed, device_specific=True)

    if accelerator.is_main_process:
        init_kwargs = {}
        if config.log_with == "wandb":
            init_kwargs["wandb"] = {"name": config.run_name}

        flat_config = flatten_config(config.to_dict())

        accelerator.init_trackers(
            project_name="IQSI",
            config=flat_config, 
            init_kwargs=init_kwargs,
        )
    logger.info(f"\n{config}")

    """
    Init train loader and test loader. 
    The train loader is used to compute the centroids and also for training the model.
    The test loader is only used for evaluation.
    """
    real_train_loader, test_loader = get_data_loader(
        real_train_data_dir=config.path.real_train_dir,
        metadata_dir=config.path.metadata_dir,
        dataset=config.dataset_name,
        bs=config.train.real_batch_size,
        n_img_per_cls=config.n_shot,
        model_type=config.model_type,
        is_rand_aug=config.is_random_aug
    )

    classes = real_train_loader.dataset.classes # get the class names from the dataset
    real_train_loader, test_loader = accelerator.prepare(real_train_loader, test_loader) # prepare the dataloaders with accelerator

    """
    Init synthetic train loader.
    You must upload the synthetic data to the path specified in config.path.synthesis_dir before running the code. 
    The synthetic data should be organized in the same way as the real data, 
    with a folder for each class containing the images for that class. 
    The synthetic data is used for training the model and is generated by a pre-trained Stable Diffusion model with lora weights. 
    """
    synth_train_loader = get_synth_train_data_loader(
        synth_train_data_dir=config.path.synthesis_dir,
        bs=config.train.synth_batch_size,
        is_rand_aug=config.train.is_rand_aug,
        target_label=config.train.target_label,
        n_img_per_cls=config.train.n_img_per_cls,
        dataset=config.dataset_name,
        n_shot=config.n_shot,
        real_train_fewshot_data_dir=config.path.fewshot_dir,
        is_pooled_fewshot=config.is_pooled_fewshot,
        model_type=config.model_type
    )

    synth_train_loader = accelerator.prepare(synth_train_loader) # prepare the synthetic train loader with accelerator

    """
    We create an infinite iterable for the synthetic train loader.
    """
    def infinite_iterable(loader):
        while True:
            for batch in loader:
                yield batch

    synth_iter = iter(infinite_iterable(synth_train_loader))

    inference_dtype = torch.float32
    if accelerator.mixed_precision == "fp16":
        inference_dtype = torch.float16
    elif accelerator.mixed_precision == "bf16":
        inference_dtype = torch.bfloat16
    
    """
    Load the Stable Diffusion pipeline with the pre-trained model and lora weights.
    We only load the unet weights with lora, and keep the vae and text encoder weights frozen.
    This is because we only use the unet for generating hard samples, 
    and we want to keep the vae and text encoder weights frozen to save memory and computation.
    """
    pipeline = StableDiffusionPipeline.from_pretrained(
        config.pretrained.model, 
        revision=config.pretrained.revision, 
        torch_dtype=inference_dtype,
        use_safetensors=True
    )

    pipeline.load_lora_weights(".", weight_name=config.unet.weight_lora)
    pipeline.fuse_lora(lora_scale=1.0)
    pipeline.unload_lora_weights()

    pipeline.vae.requires_grad_(False)
    pipeline.text_encoder.requires_grad_(False)
    pipeline.unet.requires_grad_(False)

    pipeline.scheduler = DDIMScheduler.from_config(pipeline.scheduler.config)

    pipeline.vae.enable_tiling() # enable tiling for vae to save memory during inference.
    pipeline.to(accelerator.device) # move the pipeline to the accelerator device (GPU) for faster inference.
    
    if config.use_lora:
        pipeline.unet.to(accelerator.device, dtype=inference_dtype)

    if config.allow_tf32:
        torch.backends.cuda.matmul.allow_tf32 = True

    tiny_decoder = None
    if config.pretrained.use_tiny_decoder == True:
        tiny_decoder = TinyDecoder(in_ch=4, base_ch=128)

    model = CLIP(
        dataset=config.dataset_name,
        is_lora_image=config.classifier.is_lora_image,
        is_lora_text=config.classifier.is_lora_text,
        clip_download_dir=config.classifier.clip_download_dir,
        clip_version=config.classifier.clip_version,
        precomputed_text_embs_path=config.classifier.precomputed_text_embs_path
    )

    model = accelerator.prepare(model)

    dtype_clip = model.clip.visual.conv1.weight.dtype

    if config.train.use_8bit_adam:
        try:
            import bitsandbytes as bnb
        except ImportError:
            raise ImportError(
                "Please install bitsandbytes to use 8-bit Adam. You can do so by running `pip install bitsandbytes`"
            )

        optimizer_cls = bnb.optim.AdamW8bit
    else:
        optimizer_cls = torch.optim.AdamW

    optimizer = optimizer_cls(
        model.learnable_params(),
        lr=config.train.lr,
        betas=(config.train.adam_beta1, config.train.adam_beta2),
        weight_decay=config.train.adam_weight_decay,
        eps=config.train.adam_epsilon,
    )

    autocast = contextlib.nullcontext() if config.use_lora else accelerator.autocast()

    if config.resume_from:
        logger.info(f"Resuming from {config.resume_from}")
        accelerator.load_state(config.resume_from)
        first_epoch = int(config.resume_from.split("_")[-1]) + 1
    else:
        first_epoch = 0

    step = 0

    all_real_paths = []
    for batch in real_train_loader:
        _, _, paths = batch 
        all_real_paths.extend(paths)

    _, clean_transform = get_transforms(config.model_type)
    
    """
    Compute the centroids for each class using the real training data.
    With this implementation, embeddings of each image is considered as a centroid, 
    so we have as many centroids as the number of images in the real training set.
    """
    centroids = get_centroids_from_loader_v2(model, all_real_paths, clean_transform, config.train.real_batch_size, accelerator, dtype_clip)
    centroids_tensor = torch.from_numpy(centroids).to(accelerator.device)

    for epoch in range(first_epoch, config.train.num_epochs):
        if epoch < config.train.num_epochs_warm_up:
            """
            Warm up the model for a few epochs with only the synthetic data, without using hard samples.
            """
            for real_batch in real_train_loader:
                step += 1
                
                synth_batch = next(synth_iter)
                
                train_logs = train_step(
                    model, real_batch, synth_batch, centroids_tensor, 
                    optimizer, accelerator, config, dtype_clip, autocast
                )
                
                if accelerator.is_main_process:
                    accelerator.log(train_logs, step=step)
                    
                if step % config.train.gc_steps == 0:
                    gc.collect()
                    torch.cuda.empty_cache()
        elif epoch % 2 == 0:
            """
            For every even epoch after the warm up period, we train the model with hard samples.
            """
            for real_batch in real_train_loader:
                step += 1
                synth_batch = next(synth_iter)

                train_logs, orig_imgs, hard_imgs = train_step_with_hard_samples(
                    model, pipeline, real_batch, synth_batch, centroids_tensor, 
                    optimizer, accelerator, config, dtype_clip, autocast, config.train.prop_hard, classes
                )
                
                if accelerator.is_main_process:
                    accelerator.log(train_logs, step=step)
                    if config.log_with == "wandb" and config.train.save_hard_images and step % config.train.save_hard_images_freq == 0:
                        comparison = torch.cat([orig_imgs.detach().cpu(), hard_imgs.detach().cpu()], dim=0)
                        grid = torchvision.utils.make_grid(comparison, nrow=orig_imgs.shape[0], normalize=True)

                        accelerator.log({
                            "visuals/hard_samples_comparison": wandb.Image(grid, caption=f"Step {step}: Top (Orig) vs Bottom (Hard)")
                        }, step=step)
                if step % config.train.gc_steps == 0:
                    gc.collect()
                    torch.cuda.empty_cache()
        else:
            """
            For every odd epoch after the warm up period, we train the model without hard samples, using only the synthetic data.
            """
            for real_batch in real_train_loader:
                step += 1
                
                synth_batch = next(synth_iter)
                
                train_logs = train_step(
                    model, real_batch, synth_batch, centroids_tensor, 
                    optimizer, accelerator, config, dtype_clip, autocast
                )
                
                if accelerator.is_main_process:
                    accelerator.log(train_logs, step=step)
                
                if step % config.train.gc_steps == 0:
                    gc.collect()
                    torch.cuda.empty_cache()
        
        test_acc = evaluate(model, test_loader, accelerator) # evaluate the model on the test set after each epoch to monitor the performance.
        train_acc = evaluate(model, real_train_loader, accelerator) # evaluate the model on the real training set to monitor the training performance and check for overfitting.

        accelerator.log({
            "eval/test_accuracy": test_acc,
            "eval/train accuracy": train_acc
        }, step=step)

        if (epoch + 1) % config.train.update_centroids_freq == 0:
            """
            Update the centroids every few epochs using the real training data.
            """
            centroids = get_centroids_from_loader_v2(model, all_real_paths, clean_transform, config.train.real_batch_size, accelerator, dtype_clip)
            centroids_tensor = torch.from_numpy(centroids).to(accelerator.device)
        model.train()

if __name__ == "__main__":
    app.run(main)